### ISSUE TITLE
IModelTransformer is not handling unresolved elements in finalizeTransformation()

### ISSUE THREAD

**Issue by JulijaRamoskiene** [iTwin/imodel-transformer#134]
In IModelTransformer:finalizeTransformation() unresolved elements are not logged and  forceComplete () is not called for them.

After running transformation I see this warning: 
```code
Warning | core-backend.IModelTransformer | The following elements were never fully resolved:

This indicates that either some references were excluded from the transformation
or the source has dangling references. {}
```

**Additional context**
This issue is happening because BigMap does not have keys () and values() implementation that would correctly collect keys and values.
https://github.com/iTwin/imodel-transformer/blob/main/packages/transformer/src/BigMap.ts

https://github.com/iTwin/imodel-transformer/blob/main/packages/transformer/src/IModelTransformer.ts#L1122C6-L1122C6
private finalizeTransformation() {
    if (this._partiallyCommittedEntities.size > 0) {
      Logger.logWarning(
        loggerCategory,
        [
          "The following elements were never fully resolved:",
          **[...this._partiallyCommittedEntities.keys()].join(","),**
          "This indicates that either some references were excluded from the transformation",
          "or the source has dangling references.",
        ].join("\n")
      );
      **for (const partiallyCommittedElem of this._partiallyCommittedEntities.values()) {**
        partiallyCommittedElem.forceComplete();
      }
    }

**Comment by MichaelBelousov** [comment]
Since you identified the problem, would you be willing to submit a PR fixing this @JulijaRamoskiene?

**Comment by JulijaRamoskiene** [comment]
Not at the moment, as I am a bit occupied with my current task. I will let you know if I have time in the future (to check if someone else started working on it).
