### ISSUE TITLE
skipPropagateChangesToRootElements should be default true

### ISSUE THREAD

**Issue by nick4598** [iTwin/imodel-transformer#177]
Transformation services has hit 2 issues with the 'skipPropagateChangesToRootElements' being defaulted to false so far.
- iModelDb.name property in TS changing to the rootsubject name. PullMergePush calls intiializeIModelDb which sets imodelDb.name to rootsubject.name.
- https://github.com/iTwin/imodel-transformer/issues/174

 I don't see a reason to keep it as default false, mostly because afaik there was never actually any user / consumer request to propagate changes between the root elements.

Might be worth bringing this up with the larger group as well

**Comment by JulijaRamoskiene** [comment]
Suggest to also update documentation with information that iModel name will be updated when skipPropagateChangesToRootElements is set to false: 
![image](https://github.com/iTwin/imodel-transformer/assets/28706674/a969aa68-f34a-4037-8930-01b1cde7feea)

**Comment by nick4598** [comment]
Agree its worth mentioning, thanks.

This is caused by calling initializeiModelDb after we pushChanges. initializeiModelDb updates the .name property on the iModelDb by setting it to the name of the rootsubject. Since changes to root elements are being propagated, that root subject name gets changed and leads to the iModelDb.name property being updated.
