### ISSUE TITLE
Provide hook after transformer initializes to allow consumers to run some code.

### ISSUE THREAD

**Issue by nick4598** [iTwin/imodel-transformer#180]
## Context
NOTE: Not urgent or blocking! There are already currently working workarounds in SVCs side for this.
SVCs team has a function `manualInitialize` which is used mainly for: `this._startChangesetIndex = this.synchronizationVersion.index + 1;`.

We should support SVCs team desire to determine the startChangesetIndex so that they do not have to have a `manualInitialize` which has to set a private property `_isSynchronization` on the core transformer. 

## Potential Options
- Provide a hook `onTransformerInitialized` which lets consumers run code right after the transformer is initialized and before it starts processing changes. Consumers would pass this function as part of the transformer options.
- Adding method to transformer to get the startchangesetindex?

Maybe on red arrow could add?
![image](https://github.com/iTwin/imodel-transformer/assets/22119573/89088431-e61c-4615-b98d-3f6f21aec77e)
![image](https://github.com/iTwin/imodel-transformer/assets/22119573/df39ce50-1816-4cfe-949b-4d17250cd184)
Or somewhere in this function above

## Concerns
I raised a concern on the below PR that I think could be relevant.
https://github.com/iTwin/imodel-transformer/pull/172 
>One other concern I have is, does the transformation services team ever setup the exporter manually before you call the transformer? Currently you'll need to add your custom changes before you call IModelTransformer.initialize(), which I personally ran into some trouble when trying to allow myself to do that in the tests (can look at timelinetestutil to see what changes I had to make to support that)

**Comment by JulijaRamoskiene** [comment]
To answer your question about Exporter, yes, we do set up exporter manually.
We have our custom Exporter: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel-transformations?path=/packages/imodel-transformations-local/src/Exporter.ts
Which is initialized and passed to transformer here: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel-transformations?path=/packages/imodel-transformations-local/src/transformers/TransformerFactory.ts

**Comment by nick4598** [comment]
PR linked will be to untangle initializing and calling processChanges, so consumers could run anything they wanted in between calling initialize() and process() on the transformer
