### ISSUE TITLE
Add posibility to enforce saving reverse sych version

### ISSUE THREAD

**Issue by JulijaRamoskiene** [iTwin/imodel-transformer#201]
We need transformer to save reverse synchronization version after 'process all' transformations
Currently we are doing this to make sure that reverse synchronization version is saved: 
```
// `updateSynchronizationVersion(...)` will not save reverse synchronization version if
// this is not treated as 'first synchronization'.
this["_isProvenanceInitTransform"] = true;
 >> SOME OTHER CODE <<
await this.process();
this.updateSynchronizationVersion({ force: true });
```
I explored possibility to set `wasSourceIModelCopiedToTarget` option, but it is not working as then elements are not imported.

Please add public API, or that would enable saving reverse synchronization version for all `process all` transformations.
Preserving this value is needed for partial fork workflow.

**Comment by JulijaRamoskiene** [comment]
Found an issue with code above, it can not be set before synchronization direction is determined, as invalid value might be cached. So we should have separate option that would not impact synchronization direction.

**Comment by nick4598** [comment]
I thought that there was no such thing as a processAll in the reverse sync direction (from branch to master)? Am I misremembering? I thought we only did processAll from master to branch.

**Comment by JulijaRamoskiene** [comment]
Was thinking.. since we are calling `this.updateSynchronizationVersion({ force: true });`, can we just add  additional optional argument there, to save reverse synch version? Something like  `this.updateSynchronizationVersion({ force: true, saveReverseVersion: true });`,
