### ISSUE TITLE
Transforming DisplayStyles with huge amounts of element references has a big impact on memory and performance

### ISSUE THREAD

**Issue by ViliusRuskys** [iTwin/imodel-transformer#203]
The test iModel I tested it on had 210 DisplayStyle3D Elements. Each of those had more than 250k element references in `jsonProps.excludedElements`.
Cloning each DisplayStyle takes close to 1minute of processing time (later on it takes more than that because of a different issue).

Because transformer processes definition elements first, all those references are not found in the target iModel at the moment the DisplayStyle is processed, so remapping them is impossible and the DisplayStyle is inserted as a "partial element". Currently transformer is very inefficient in storing the partially committed entity references and in this specific scenario it amounts to a large performance hit and requires a lot of memory.

**Comment by MichaelBelousov** [comment]
I actually recorded this proposal already in the last bullet point here: 
https://github.com/iTwin/imodel-transformer/issues/83#issue-1774935962
