### ISSUE TITLE
[fed guid optimization] fix bug where there is an infinite loop processing changes for elements where the source has no fedguid (this may be fixed by properly supporting mixed provenance)

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/imodel-transformer#40]
possibly fixed by #39, @ViliusRuskys has a reproduction, but tests for #39 once complete likely cover this

**Comment by MichaelBelousov** [comment]
this doesn't appear to be reproducible in the default transformer, but there is another failure which could be related.

**Comment by MichaelBelousov** [comment]
@ViliusRuskys can I close this as not in the default transformer?

**Comment by ViliusRuskys** [comment]
Issue fixed in #57
