### ISSUE TITLE
Foreign Key Constraint error when deleting an element that is referenced in other elements as code scope

### ISSUE THREAD

**Issue by DeividasDavidav** [iTwin/imodel-transformer#61]
**Describe the bug**
When using onDeleteElement() function from IModelImporter to delete an element, if an element is referenced by other elements in their code scopes, it throws Foreign key constraint error. That is because ElementTreeDeleter doesn't find elements with code scope references to specific element when deleting it. (Already created an issue with possible solution in itwins-core (https://github.com/iTwin/itwinjs-core/issues/5576) but they said that ElementTreeDeleter shouldn't solve this relationship issue)

**To Reproduce**
1. Create the first element
2. Create the second element that references the first element in its code scope
3. Try to delete the first element (can use onDeleteElement() from IModelImporter)
4. See "error deleting element" error (errorNumber: 65553)

**Expected behavior**
When deleting an element, it should also process the elements that reference the element in their code scopes.

**Desktop (please complete the applicable information):**

- iTwin.js Version 3.6.1
- Node Version 18.16.0

**Comment by MichaelBelousov** [comment]
We can port your suggested fix to a `ElementCascadingDeleter` in the transformer. Given you already have sample fix code in your original core issue, would you be willing to make a PR?

Do we need to add additional sanity checks though that the transformer should only delete this element if its other references (the scope one that currently errors) are also being deleted?

**Comment by MichaelBelousov** [comment]
this was fixed by #75, closing
