### ISSUE TITLE
ignore init fork changesets during synchronizations

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/imodel-transformer#84]
initialize fork changesets are expensive since they can potentially update all elements (since an aspect was added), but by design can be ignored during synchronizations

**Comment by nick4598** [comment]
This is fixed as of this PR: https://github.com/iTwin/imodel-transformer/pull/154/files#diff-d07eab136b812db5c475ddb91cbc589d5fd6e5943638c6e2028994d6f58fe80b which checks for isProvenanceInitTransform being true and adds the init fork changesets to the pendingReverseSyncIndices
